name: CI/CD Pipeline

# Otomatis jalan setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Jalankan di server Linux

    steps:
    # 1. Ambil kode Anda dari GitHub
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Login ke Docker Hub (pakai secret)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build dan Push image Backend
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./BackEnd # Lokasi Dockerfile backend
        file: ./BackEnd/Dockerfile
        push: true
        tags: driansyh/todo-backend:latest 

    # 4. Build dan Push image Frontend
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend # Lokasi Dockerfile frontend
        file: ./frontend/Dockerfile
        push: true
        tags: driansyh/todo-frontend:latest